steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg=DOCKER_BUILDKIT=1'
      - '-f'
      - 'Dockerfile.rethinkdb'
      - '--progress=plain'
      - '--compress'
      #- '--squash'
      - '-t'
      - 'europe-southwest1-docker.pkg.dev/rosepetal-dev/test-repo/rosepetal-dep-proves:latest'
      - '-t'
      - 'europe-southwest1-docker.pkg.dev/rosepetal-dev/test-repo/rosepetal-dep-proves:$_TAG'
      - '.'
    env:
      - 'DOCKER_BUILDKIT=1'

images:
  - 'europe-southwest1-docker.pkg.dev/rosepetal-dev/test-repo/rosepetal-dep-proves:latest'
  - 'europe-southwest1-docker.pkg.dev/rosepetal-dev/test-repo/rosepetal-dep-proves:$_TAG'

substitutions:
  _TAG: 'v.1.0.0'
