name: Build Artifacts

on:
  push:
    branches:
      - main

jobs:
  build_artifacts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: fem un build al google cloud artifacts
        run: ./build_script
