name: Build Artifacts

on:
  push:
    branches:
      - main

jobs:
  build_artifacts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Instal·lar Google Cloud SDK
        run: curl -sSL https://sdk.cloud.google.com | bash

      - name: 'Autenticar-se amb Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CLOUD_KEY_FILE }}'

      - name: Enviar la construcció a Google Cloud Build
        run: gcloud builds submit --config=./cloudbuild.yaml .
