name: Build Artifacts

on:
  push:
    branches:
      - main

jobs:

  build_artifacts:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 'Autenticar-se amb Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CLOUD_KEY_FILE }}'

      - name: Extract latest version tag
        id: extract_tag
        run: |
          IMAGE="europe-southwest1-docker.pkg.dev/rosepetal-dev/rosepetal-dep/rosepetal-dep-ajenti"
          digest=$(gcloud artifacts docker tags list "$IMAGE" | grep latest | awk '{print $3}')

          echo "Digest: $digest"

          echo "Looking for version tag(s) matching this digest..."
          version_tag=$(gcloud artifacts docker tags list "$IMAGE"| grep "$digest" | grep v. | awk '{print $1}')

          echo "Found version tag: $version_tag"
          {echo "version_tag<<EOF"
          echo "$version_tag"
          echo "EOF" } >> "$GITHUB_OUTPUT"
      - name: Enviar la construcció a Google Cloud Build
        run: gcloud builds submit --config=cloudbuild.yaml .
