#Aquest github actions té per objectiu el build automàtic de noves versions de les imatges a Cloud Build respectant les versions actuals
name: Build Artifacts

on:
  push:
    branches:
      - main

jobs:

  build_artifacts:
    runs-on: ubuntu-latest
    steps:
      #Agafem tots els fitxers del repositori
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 'Autenticar-se amb Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CLOUD_KEY_FILE }}'

      - name: Set up Google Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Trobar el tag de la versio (v.x.x.x)
        id: extract_tag
        run: |
          IMAGE="europe-southwest1-docker.pkg.dev/rosepetal-dev/rosepetal-dep/rosepetal-dep-ajenti"
          digest=$(gcloud artifacts docker tags list "$IMAGE" | grep latest | awk '{print $3}')
          if [[ -z "$digest" ]]; then
            echo "Encara no hi ha cap imatge penjada"
            echo "tag=v.1.0.0" >> $GITHUB_OUTPUT
          else
            echo "Digest: $digest"
            echo "Looking for version tag(s) matching this digest..."
            version_tag=$(gcloud artifacts docker tags list "$IMAGE"| grep "$digest" | grep '^v\.' | awk '{print $1}')
            if [[ -z "$version_tag" ]]; then
              echo "Existing image with no v.x.x.x tag. Check Artifacts repository. This might be an inconsistency. Abording..."
              exit 1
            fi
            #Extraiem la part numèrica per fer un upgrade del tag
            NUMERIC_PART=${version_tag#v.}
            IFS='.' read -r -a version_parts <<< "$NUMERIC_PART"
            major=${version_parts[0]}
            minor=${version_parts[1]}
            patch=${version_parts[2]}

            new_patch=$((patch+1))

            INCREMENTED_TAG="v.$major.$minor.$new_patch"
            
            echo "tag=$INCREMENTED_TAG" >> $GITHUB_OUTPUT
          fi
      - name: Enviar la construcció a Google Cloud Build
        run: gcloud builds submit --config=cloudbuild.yaml --substitutions=_TAG=${{ steps.extract_tag.outputs.tag }}
