name: Build Artifacts

on:
  push:
    branches:
      - main

env:
  REGION: europe-southwest1
  PROJECT_ID: rosepetal-dev
  REPO: test-repo
  IMAGE_NAME: rosepetal-dep-proves
  SOURCE_IMAGE_NAME: rosepetal-dep-ajenti
  ARTIFACT_PATH: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE_NAME }}
  SOURCE_ARTIFACT_PATH: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/rosepetal-dep/${{ env.SOURCE_IMAGE_NAME }}

jobs:
  build_artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CLOUD_KEY_FILE }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Extract version tag (v.x.x.x)
        id: extract_tag
        run: |
          IMAGE="${{ env.SOURCE_ARTIFACT_PATH }}"
          digest=$(gcloud artifacts docker tags list "$IMAGE" | grep latest | awk '{print $3}')
          if [[ -z "$digest" ]]; then
            echo "tag=v.1.0.0" >> $GITHUB_OUTPUT
          else
            version_tag=$(gcloud artifacts docker tags list "$IMAGE" | grep "$digest" | grep '^v\.' | awk '{print $1}')
            if [[ -z "$version_tag" ]]; then
              echo "No v.x.x.x tag found. Inconsistent image. Aborting..."
              exit 1
            fi
            NUMERIC_PART=${version_tag#v.}
            IFS='.' read -r -a version_parts <<< "$NUMERIC_PART"
            major=${version_parts[0]}
            minor=${version_parts[1]}
            patch=${version_parts[2]}
            new_patch=$((patch+1))
            INCREMENTED_TAG="v.$major.$minor.$new_patch"
            echo "tag=$INCREMENTED_TAG" >> $GITHUB_OUTPUT
          fi

      - name: Build Docker image
        run: |
          docker build \
            --build-arg=DOCKER_BUILDKIT=1 \
            -f Dockerfile.rethinkdb \
            --progress=plain \
            --compress \
            -t ${{ env.ARTIFACT_PATH }}:latest \
            -t ${{ env.ARTIFACT_PATH }}:${{ steps.extract_tag.outputs.tag }} \
            .

      - name: Push Docker images
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
          docker push ${{ env.ARTIFACT_PATH }}:latest
          docker push ${{ env.ARTIFACT_PATH }}:${{ steps.extract_tag.outputs.tag }}
